# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'rspec', '~> 3.11'

gem 'rake', '~> 13.0'

gem 'dry-initializer', '~> 3.1'
gem 'dry-struct', '~> 1.4'

gem 'activerecord', '~> 7.0'
gem 'mysql2', '~> 0.5.4'
gem 'sequel', '~> 5.60'

gem 'dotenv', '~> 2.8'
