# frozen_string_literal: true

require 'sequel'
require_relative 'lib/paymium_market'

DATABASE = Sequel.connect(
  :adapter => 'mysql2',
  :user => ENV['DB_USERNAME'],
  :host => ENV['DB_HOST'],
  :database => ENV['DATABASE'] ,
  :password=>ENV['DB_PASSWORD'])


desc 'database setup'
task :setup_db do
  unless DATABASE.table_exists?(:users)
    DATABASE.create_table :users do
      primary_key :id

      column :eur, String
      column :btc, String
    end
  end

  unless DATABASE.table_exists?(:orders)
    DATABASE.create_table :orders do
      primary_key :id
      foreign_key :user_id, :users

      column :amount, String
      column :price, String
      column :side, String
      column :state, String
      column :market, String
    end
  end

  DATABASE[:users].insert(eur: '45000', btc: '10')
  DATABASE[:users].insert(eur: '1200', btc: '0.02')
end

task :clear_db do
  DATABASE[:orders].delete
  DATABASE[:users].delete
end
